
export const products = [
    {
      id: 1,
      title: "book",
      description: "For students",
      price: "250",
      img: "./images/book.png",
      quantity: 1,
    },
    {
      id: 2,
      title: "jacket",
      description: "Teenage trends",
      price: "2300",
      img: "./images/jacket.png",
      quantity: 1,
    },
    {
      id: 3,
      title: "Redmi 9",
      description: "black in color",
      price: "19500",
      img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "jewelry",
      description: "women's collection",
      price: "90500",
      img: "./images/jewelry.png",
      quantity: 1,
    },
    {
      id: 5,
      title: "jar",
      description: "for kitchen",
      price: "350",
      img: "./images/jar.png",
      quantity: 1,
    },
    {
      id: 6,
      title: "Iphone 12",
      description: "Best mobile ever",
      price: "90500",
      img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "jelly",
      description: "healthy jelly",
      price: "100",
      img: "./images/jelly.png",
      quantity: 1,
    },
  ];